---
apiVersion: datasciencepipelinesapplications.opendatahub.io/v1
kind: DataSciencePipelinesApplication
metadata:
  name: dspa
spec:
  apiServer:
    artifactSignedURLExpirySeconds: 60
    caBundleFileMountPath: ''
    caBundleFileName: ''
    deploy: true
    enableOauth: true
    enableSamplePipeline: false
    {{- with .Values.managedPipelines }}
    managedPipelines:
      {{- toYaml . | nindent 6 }}
    {{- end }}
  database:
    disableHealthCheck: false
    mariaDB:
      deploy: true
      pipelineDBName: mlpipeline
      pvcSize: 10Gi
      username: mlpipeline
  dspVersion: v2
  objectStorage:
    disableHealthCheck: false
    enableExternalRoute: false
    externalStorage:  # points to the bundled S4 service or caller-provided storage
{{- $storage := .Values.pipelineStorage.externalStorage | deepCopy }}
{{- if .Values.pipelineStorage.deployAwsCompatibleStorage }}
{{- $_ := set $storage "host" (printf "s4.%s.svc.cluster.local" .Release.Namespace) }}
{{- end }}
{{ toYaml $storage | indent 6 }}
  persistenceAgent:
    deploy: true
    numWorkers: 2
  podToPodTLS: true
  scheduledWorkflow:
    cronScheduleTimezone: UTC
    deploy: true
