{{- if and .Values.notebook.create .Values.secret.create }}
# This secret will be used by the rag-pipeline-notebook
---
apiVersion: v1
kind: Secret
metadata:
  name: rag-ingestion-pipeline-secret
  annotations: {}
  labels:
    opendatahub.io/dashboard: 'true'
stringData:
  SOURCE: S3
  EMBEDDING_MODEL: {{ .Values.notebook.embedding_model }}
  NAME:  {{ .Values.notebook.name }}
  VERSION:  "{{ .Values.notebook.version }}"
{{- if .Values.pipelineStorage.deployAwsCompatibleStorage }}
  ACCESS_KEY_ID: "{{ index .Values "aws-compatible-storage" "s3" "accessKeyId" }}"
  SECRET_ACCESS_KEY: "{{ index .Values "aws-compatible-storage" "s3" "secretAccessKey" }}"
{{- else }}
  ACCESS_KEY_ID: "{{ .Values.notebook.s3.accessKeyId }}"
  SECRET_ACCESS_KEY: "{{ .Values.notebook.s3.secretAccessKey }}"
{{- end }}
{{- if .Values.pipelineStorage.deployAwsCompatibleStorage }}
  ENDPOINT_URL: "http://s4.{{ .Release.Namespace }}.svc.cluster.local:7480"
{{- else }}
  ENDPOINT_URL: "{{ .Values.pipelineStorage.externalStorage.scheme }}://{{ .Values.pipelineStorage.externalStorage.host }}:{{ .Values.pipelineStorage.externalStorage.port }}"
{{- end }}
  BUCKET_NAME: {{ .Values.notebook.s3.bucket_name }}
  REGION: {{ .Values.notebook.s3.region }}
{{- end }}
