{{- if and .Values.notebook.create .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: rag-pipeline-secrets
type: Opaque
stringData:
{{- if .Values.pipelineStorage.deployAwsCompatibleStorage }}
  AWS_S3_ENDPOINT: "http://s4.{{ .Release.Namespace }}.svc.cluster.local:7480"
{{- else }}
  AWS_S3_ENDPOINT: "{{ .Values.pipelineStorage.externalStorage.scheme }}://{{ .Values.pipelineStorage.externalStorage.host }}:{{ .Values.pipelineStorage.externalStorage.port }}"
{{- end }}
  LLAMASTACK_BASE_URL: "http://llamastack.{{ .Release.Namespace }}.svc.cluster.local:8321"
  OGX_AI_BASE_URL: "http://ogx-ai.{{ .Release.Namespace }}.svc.cluster.local:8321"
  DS_PIPELINE_URL: "https://ds-pipeline-dspa.{{ .Release.Namespace }}.svc.cluster.local:8888"
{{- end }}
